default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASSWORD'] %>

development:
  <<: *default
  database: list_api_development
  host: localhost

test:
  <<: *default
  database: list_api_test
  host: localhost

production:
  <<: *default
  database: list_api_production
  username: list_api
  password: <%= ENV['LIST_API_DATABASE_PASSWORD'] %>
